access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://Kavith:Kavith101$@cluster0.gwltomc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Cluster0
server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
